### ISSUE TITLE
Which License? AKA Can I use your code inside my own?

### ISSUE THREAD

**Issue by OlafHaag** [wOOL/STSC#1]
Hey! There's no explicit license attached to the code. Can I use it and if so, under which conditions?
I'd like to use your stsc code within my own code project and if possible distribute my project under the MIT License.
Could you please specify the license? Otherwise, I can view and fork it, but not do much else with it.
Thanks!

**Comment by wOOL** [comment]
Oh. I added a license file. 

https://github.com/wOOL/STSC/blob/master/LICENSE

Basically you can do whatever you want, not even necessarily mentioning the source.

**Comment by OlafHaag** [comment]
Thank you so much! Saved my day!
